CREATE OR REPLACE TRIGGER MAX_JUGADORES
  
    FOR INSERT OR UPDATE ON JUGAR_PARA 
    
    COMPOUND TRIGGER
    NEW_JUGADOR JUGAR_PARA%ROWTYPE;
 
    V_CANTIDADJUGADORES NUMBER;
    
    BEFORE EACH ROW IS
    BEGIN
    IF INSERTING THEN
    NEW_JUGADOR.COD_JUGADOR:= :NEW.COD_JUGADOR;
    NEW_JUGADOR.COD_EQUIPO:= :NEW.COD_EQUIPO;
    
    ELSE
    
    NEW_JUGADOR.COD_EQUIPO:= :NEW.COD_EQUIPO;
    END IF;
    
    END BEFORE EACH ROW;
    
    AFTER STATEMENT IS
    BEGIN
    
    SELECT COUNT(*) INTO  V_CANTIDADJUGADORES
    FROM JUGAR_PARA
    WHERE COD_EQUIPO=NEW_JUGADOR.COD_EQUIPO;
    
    DBMS_OUTPUT.PUT_LINE(V_CANTIDADJUGADORES);
    
    IF V_CANTIDADJUGADORES>=6 THEN
    
    RAISE_APPLICATION_ERROR(-20100,'Error,solo puede haver 6 jugadores por equipo');
    
    END IF;
    
    END AFTER STATEMENT;
    
    END MAX_JUGADORES;
    



