CREATE OR REPLACE TRIGGER T_CERRAR_CALENDARIO
    BEFORE UPDATE OF ABIERTA
    ON TEMPORADAS
    FOR EACH ROW 
DECLARE 
    E_POCOS_JUGADORES EXCEPTION;
    V_MENSAJE_EQUIPOS VARCHAR(250);
    V_ERRROR_EQUIPOS BOOLEAN := FALSE;
BEGIN
    IF(TO_CHAR(:NEW.ABIERTA) == 'N') 
    THEN
        DECLARE 
            CURSOR EQUIPOS_INCORRECTOS IS (
                SELECT COD_EQUIPO
                FROM JUGAR_PARA
                GROUP BY COD_EQUIPO
                HAVING COUNT(COD_JUGADOR) < 2);
        BEGIN
            FOR V_COD_EQUIPO IN EQUIPOS_INCORRECTOS LOOP
                V_MENSAJE_EQUIPOS := V_MENSAJE || V_COD_EQUIPO;
                V_ERRROR_EQUIPOS := TRUE;
            END LOOP;
        END;
        
        IF V_ERRROR
        THEN
            RAISE E_POCOS_JUGADORES;
        END IF;
    END IF;
EXCEPTION 
    WHEN E_POCOS_JUGADORES THEN
        RAISE_APPLICATION_ERROR(-20015, 'ERROR. HACEN FALTA MÁS JUGADORES EN 
            LOS SIGUIENTES EQUIPOS' || V_MENSAJE_EQUIPOS);       
END;

