CREATE OR REPLACE TRIGGER COMPROBAR_CERRADO_CALENDARIO
BEFORE INSERT OR UPDATE ON EQUIPOS
FOR EACH ROW
  DECLARE
 
  V_ABIERTA TEMPORADAS.ABIERTA%TYPE;
  E_CALENDARIOCERRADO EXCEPTION;
  
  BEGIN
  SELECT ABIERTA INTO V_ABIERTA
  FROM TEMPORADAS
  WHERE COD_TEMPORADA = (SELECT MAX(COD_TEMPORADA)
                         FROM TEMPORADAS);
  
  IF UPPER(V_ABIERTA)='N' THEN
    RAISE  E_CALENDARIOCERRADO;  
  END IF;
  
  EXCEPTION
  WHEN E_CALENDARIOCERRADO THEN
    RAISE_APPLICATION_ERROR (-20123,'Error.El calendario esta cerrado');
  END COMPROBAR_CERRADO_CALENDARIO;
  
CREATE OR REPLACE TRIGGER C_CERRADO_CAL_JUG
BEFORE INSERT OR UPDATE ON JUGADORES
FOR EACH ROW
  DECLARE
 
  V_ABIERTA TEMPORADAS.ABIERTA%TYPE;
  E_CALENDARIOCERRADO EXCEPTION;
  
  BEGIN
  SELECT ABIERTA INTO V_ABIERTA
  FROM TEMPORADAS
  WHERE COD_TEMPORADA = (SELECT MAX(COD_TEMPORADA)
                         FROM TEMPORADAS);
  
  IF UPPER(V_ABIERTA)='N' THEN
    RAISE  E_CALENDARIOCERRADO;  
  END IF;
  
  EXCEPTION
  WHEN E_CALENDARIOCERRADO THEN
    RAISE_APPLICATION_ERROR (-20123,'Error.El calendario esta cerrado');
  END C_CERRADO_CAL_JUG;