-- GESTIONAR_JORNADAS_TEST
/* 
 Fecha: 03/05/2022
 Descripcion:  Testeo paquete gestion de jornadas
 */
 
SET SERVEROUTPUT ON;

DECLARE
    P_COD_TEMPORADA NUMBER(2) := 01;
    P_FECHA_JORNADA DATE := TO_DATE('04/11/2022','DD/MM/YYYY');
BEGIN
    GEST_JORNADAS.INSERT_JORNADA(P_COD_TEMPORADA, P_FECHA_JORNADA); 
END;


 -- genera error de nombre de equipo duplicado
DECLARE
    P_COD_TEMPORADA NUMBER(2) := 05;
    P_FECHA_JORNADA DATE := TO_DATE('04/11/2022','DD/MM/YYYY');
BEGIN
    GEST_JORNADAS.INSERT_JORNADA(P_COD_TEMPORADA, P_FECHA_JORNADA); 
END;

SELECT * FROM TEMPORADAS;
SELECT * FROM JORNADAS;

--ROLLBACK;