-- GESTIONAR_USUARIOS_TEST
/* 
 Fecha: 17/05/2022
 Descripcion:  Testeo paquete gestion de usuarios
 */
 
SET SERVEROUTPUT ON;

DECLARE
   P_NOMBRE VARCHAR2(15) := 'Alba';
   P_FECHA_NACIMIENTO DATE := TO_DATE('03/05/1998','DD/MM/YYYY');
   P_PASSWORD VARCHAR2(20) := 'Hola';
   P_EMAIL VARCHAR2(30) := 'alba@gmail.com';
BEGIN
    GEST_USUARIOS.INSERT_USUARIO(P_NOMBRE, P_FECHA_NACIMIENTO, 
            P_PASSWORD, P_EMAIL); 
END;

DECLARE
   P_NOMBRE VARCHAR2(15) := 'Admin';
   P_FECHA_NACIMIENTO DATE := TO_DATE('03/05/1998','DD/MM/YYYY');
   P_PASSWORD VARCHAR2(20) := 'admin';
   P_EMAIL VARCHAR2(30) := 'admin@gmail.com';
BEGIN
    GEST_USUARIOS.INSERT_ADMINISTRADOR(P_NOMBRE, P_FECHA_NACIMIENTO, 
            P_PASSWORD, P_EMAIL); 
END;

SELECT * FROM USUARIOS;


--ROLLBACK;