CREATE OR REPLACE FUNCTION LOG_IN(USERNAME IN VARCHAR2, PASSWD IN VARCHAR2)
RETURN VARCHAR2
AS
  MATCH_COUNT NUMBER;
  INCORRECTO EXCEPTION;
  DUPLICADO EXCEPTION;
BEGIN
  SELECT COUNT(*)
    INTO MATCH_COUNT
    FROM USUARIOS
    WHERE EMAIL=USERNAME
    AND PASSWORD_=PASSWD;
  IF MATCH_COUNT = 0 THEN
    RAISE INCORRECTO;
  ELSIF MATCH_COUNT = 1 THEN
    RETURN 'LOGIN SUCCESSFUL!';
  ELSE
    RAISE DUPLICADO;
  END IF;
EXCEPTION
    WHEN INCORRECTO THEN
        RAISE_APPLICATION_ERROR (-20054 ,'Err. emai o contrasena incorrecta');
    WHEN DUPLICADO THEN
        RAISE_APPLICATION_ERROR (-20054 ,'Err. email duplicado');
	WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20999,'Error desconocido');
END;


SELECT log_in('alba@gmail.com', 'Hola') FROM dual;

SELECT log_in('admin@gmail.com', 'admin') FROM dual;